Traceback (most recent call last):
  File "/Volumes/Seagate/monotrac/nextflow/bin/depth_plots.py", line 25, in <module>
    g = sns.FacetGrid(plotting_data, col='GeneID', col_wrap=5, height=4)  
  File "/opt/anaconda3/envs/medaka/lib/python3.8/site-packages/seaborn/axisgrid.py", line 482, in __init__
    axes[0] = fig.add_subplot(nrow, ncol, 1, **subplot_kws)
  File "/opt/anaconda3/envs/medaka/lib/python3.8/site-packages/matplotlib/figure.py", line 768, in add_subplot
    ax = projection_class(self, *args, **pkw)
  File "/opt/anaconda3/envs/medaka/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 644, in __init__
    subplotspec = SubplotSpec._from_subplot_args(fig, args)
  File "/opt/anaconda3/envs/medaka/lib/python3.8/site-packages/matplotlib/gridspec.py", line 589, in _from_subplot_args
    gs = GridSpec._check_gridspec_exists(figure, rows, cols)
  File "/opt/anaconda3/envs/medaka/lib/python3.8/site-packages/matplotlib/gridspec.py", line 226, in _check_gridspec_exists
    return GridSpec(nrows, ncols, figure=figure)
  File "/opt/anaconda3/envs/medaka/lib/python3.8/site-packages/matplotlib/gridspec.py", line 379, in __init__
    super().__init__(nrows, ncols,
  File "/opt/anaconda3/envs/medaka/lib/python3.8/site-packages/matplotlib/gridspec.py", line 49, in __init__
    raise ValueError(
ValueError: Number of rows must be a positive integer, not 0
